### ISSUE TITLE
substitution not working inside user doc.

### ISSUE THREAD

**Issue by DALDEI** [okapies/hoc2js#1]
java -jar hoc2js*.jar
```

a=b
b=${a}

Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: Reader: 2: Could not resolve substitution to a value: ${a}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:87)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:340)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:279)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:320)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:24)
        at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:149)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:70)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:33)
        at com.github.okapies.hoc2js.Hoc2Js.main(Hoc2Js.java:33)
```

Works fine when referencing existing built in conf

java ...
```

a=${hoc2js.render}


{"a":{"comments":false,"formatted":false,"originComments":false,"json":true}}

```

**Comment by jcii** [comment]
I'm seeing the same with this test.conf file:
```
project: CM
component: Other
item: ${project}
```
which throws this error:
```
Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: test.conf: 3: Could not resolve substitution to a value: ${project}
```
